# Generated by Django 5.2.15 on 2026-07-07 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_name', models.CharField(max_length=150)),
                ('category', models.CharField(choices=[('Office', 'Office'), ('Salary', 'Salary'), ('Marketing', 'Marketing'), ('Travel', 'Travel'), ('Food', 'Food'), ('Software', 'Software'), ('Utilities', 'Utilities'), ('Others', 'Others')], max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_mode', models.CharField(choices=[('Cash', 'Cash'), ('UPI', 'UPI'), ('Bank', 'Bank Transfer'), ('Card', 'Card'), ('Cheque', 'Cheque')], max_length=20)),
                ('expense_date', models.DateField()),
                ('description', models.TextField(blank=True, null=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='expenses/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Expense',
                'verbose_name_plural': 'Expenses',
                'ordering': ['-id'],
            },
        ),
    ]
