# Generated by Django 5.2.15 on 2026-07-22 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_expense_bank_name_expense_cheque_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='custom_denomination',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='denomination',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='notes_count',
        ),
        migrations.CreateModel(
            name='CashDenomination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denomination', models.IntegerField(choices=[(500, '₹500'), (200, '₹200'), (100, '₹100'), (50, '₹50'), (20, '₹20'), (10, '₹10')])),
                ('notes_count', models.PositiveIntegerField()),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_denominations', to='expenses.expense')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
