# Generated by Django 5.2.15 on 2026-07-11 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_alter_employeesalary_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectexpense',
            name='payment_mode',
            field=models.CharField(choices=[('Cash', 'Cash'), ('UPI', 'UPI'), ('Bank', 'Bank Transfer'), ('Card', 'Card'), ('Cheque', 'Cheque')], default='Cash', max_length=20),
            preserve_default=False,
        ),
    ]
