# Generated by Django 5.2.15 on 2026-07-11 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_projectexpense_payment_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeesalary',
            name='employee_id',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
