# Generated by Django 5.2.15 on 2026-07-13 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_projectpayment_bank_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectexpense',
            name='bank_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='projectexpense',
            name='cheque_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='projectexpense',
            name='custom_denomination',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='projectexpense',
            name='denomination',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='projectexpense',
            name='notes_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectexpense',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
