# Generated by Django 5.2.15 on 2026-07-13 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_projectexpense_bank_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeesalary',
            name='bank_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='employeesalary',
            name='cheque_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employeesalary',
            name='custom_denomination',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='employeesalary',
            name='denomination',
            field=models.CharField(blank=True, choices=[('100', '₹100'), ('200', '₹200'), ('500', '₹500'), ('Others', 'Others')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='employeesalary',
            name='notes_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeesalary',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
