# Generated by Django 5.2.15 on 2026-07-22 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_employeesalary_bank_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeesalary',
            name='custom_denomination',
        ),
        migrations.RemoveField(
            model_name='employeesalary',
            name='denomination',
        ),
        migrations.RemoveField(
            model_name='employeesalary',
            name='notes_count',
        ),
        migrations.RemoveField(
            model_name='projectexpense',
            name='custom_denomination',
        ),
        migrations.RemoveField(
            model_name='projectexpense',
            name='denomination',
        ),
        migrations.RemoveField(
            model_name='projectexpense',
            name='notes_count',
        ),
        migrations.RemoveField(
            model_name='projectpayment',
            name='custom_denomination',
        ),
        migrations.RemoveField(
            model_name='projectpayment',
            name='denomination',
        ),
        migrations.RemoveField(
            model_name='projectpayment',
            name='notes_count',
        ),
        migrations.CreateModel(
            name='EmployeeSalaryCashDenomination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denomination', models.IntegerField()),
                ('notes_count', models.PositiveIntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('salary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_denominations', to='services.employeesalary')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectExpenseCashDenomination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denomination', models.IntegerField()),
                ('notes_count', models.PositiveIntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_denominations', to='services.projectexpense')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectPaymentCashDenomination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denomination', models.IntegerField()),
                ('notes_count', models.PositiveIntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_denominations', to='services.projectpayment')),
            ],
        ),
    ]
