# Generated by Django 5.2.15 on 2026-07-22 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_remove_employeesalary_custom_denomination_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectpaymentcashdenomination',
            name='denomination',
            field=models.IntegerField(choices=[(500, '₹500'), (200, '₹200'), (100, '₹100'), (50, '₹50'), (20, '₹20'), (10, '₹10')]),
        ),
    ]
