# Generated by Django 5.2.15 on 2026-07-22 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0010_alter_projectpaymentcashdenomination_denomination'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeesalarycashdenomination',
            name='denomination',
            field=models.IntegerField(choices=[(500, '₹500'), (200, '₹200'), (100, '₹100'), (50, '₹50'), (20, '₹20'), (10, '₹10')]),
        ),
        migrations.AlterField(
            model_name='projectexpensecashdenomination',
            name='denomination',
            field=models.IntegerField(choices=[(500, '₹500'), (200, '₹200'), (100, '₹100'), (50, '₹50'), (20, '₹20'), (10, '₹10')]),
        ),
    ]
