# Generated by Django 5.2.15 on 2026-07-22 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0011_alter_employeesalarycashdenomination_denomination_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeesalary',
            name='net_salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
