# Generated by Django 5.2.15 on 2026-07-07 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('month', models.CharField(max_length=20)),
                ('year', models.PositiveIntegerField()),
                ('revenue_target', models.DecimalField(decimal_places=2, max_digits=12)),
                ('expense_budget', models.DecimalField(decimal_places=2, max_digits=12)),
                ('profit_target', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
            options={
                'ordering': ['-year', '-month'],
            },
        ),
    ]
