# Generated by Django 5.2.15 on 2026-07-11 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_monthlytarget_options_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='monthlytarget',
            index=models.Index(fields=['year'], name='dashboard_m_year_c2678c_idx'),
        ),
        migrations.AddIndex(
            model_name='monthlytarget',
            index=models.Index(fields=['month'], name='dashboard_m_month_1ee7e7_idx'),
        ),
    ]
