# Generated by Django 5.2.15 on 2026-07-11 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_alter_transaction_options_transaction_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('Completed', 'Completed'), ('Pending', 'Pending'), ('Paid', 'Paid'), ('Failed', 'Failed')], default='Completed', max_length=20),
        ),
    ]
