# Generated by Django 5.2.15 on 2026-07-11 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlytarget',
            name='month',
            field=models.CharField(choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], max_length=20),
        ),
        migrations.AlterField(
            model_name='monthlytarget',
            name='year',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='monthlytarget',
            unique_together={('month', 'year')},
        ),
    ]
