# Generated by Django 5.2.15 on 2026-07-12 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0002_alter_monthlytarget_month_alter_monthlytarget_year_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reminder',
            options={'ordering': ['reminder_date', '-created_at']},
        ),
        migrations.RemoveField(
            model_name='reminder',
            name='is_completed',
        ),
        migrations.AddField(
            model_name='reminder',
            name='module',
            field=models.CharField(choices=[('Training', 'Training'), ('Income', 'Income'), ('Expense', 'Expense'), ('Services', 'Services'), ('Transaction', 'Transaction'), ('General', 'General')], default='General', max_length=30),
        ),
        migrations.AddField(
            model_name='reminder',
            name='priority',
            field=models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], default='Medium', max_length=20),
        ),
        migrations.AddField(
            model_name='reminder',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed')], default='Pending', max_length=20),
        ),
    ]
