# Generated by Django 5.2.15 on 2026-07-12 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0003_alter_reminder_options_remove_reminder_is_completed_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('achieved_date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Achieved', 'Achieved')], default='Achieved', max_length=20)),
            ],
            options={
                'ordering': ['-achieved_date', '-id'],
            },
        ),
    ]
