# Generated by Django 5.2.15 on 2026-07-12 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0004_achievement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='action',
            field=models.CharField(choices=[('Add', 'Add'), ('Edit', 'Edit'), ('Delete', 'Delete'), ('View', 'View'), ('Reminder', 'Reminder'), ('Target', 'Target'), ('Achievement', 'Achievement'), ('Login', 'Login'), ('Logout', 'Logout')], max_length=30),
        ),
        migrations.AlterField(
            model_name='notification',
            name='module',
            field=models.CharField(choices=[('Accounts', 'Accounts'), ('Income', 'Income'), ('Expense', 'Expense'), ('Training', 'Training'), ('Services', 'Services'), ('Transaction', 'Transaction'), ('Report', 'Report'), ('Settings', 'Settings'), ('System', 'System')], max_length=30),
        ),
    ]
