# Generated by Django 5.2.15 on 2026-07-10 04:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(1, message='Amount must be greater than zero.')]),
        ),
        migrations.AlterField(
            model_name='income',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='income/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])]),
        ),
    ]
