# Generated by Django 5.2.15 on 2026-07-22 04:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0003_income_bank_name_income_cheque_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashDenomination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('denomination', models.CharField(choices=[('2000', '₹2000'), ('500', '₹500'), ('200', '₹200'), ('100', '₹100'), ('50', '₹50'), ('20', '₹20'), ('10', '₹10'), ('Other', 'Other')], max_length=20)),
                ('custom_denomination', models.PositiveIntegerField(blank=True, null=True)),
                ('notes_count', models.PositiveIntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('income', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_denominations', to='income.income')),
            ],
            options={
                'verbose_name': 'Cash Denomination',
                'verbose_name_plural': 'Cash Denominations',
                'ordering': ['id'],
            },
        ),
    ]
