# Generated by Django 5.2.15 on 2026-07-22 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0004_cashdenomination'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='income',
            name='custom_denomination',
        ),
        migrations.RemoveField(
            model_name='income',
            name='denomination',
        ),
        migrations.RemoveField(
            model_name='income',
            name='notes_count',
        ),
    ]
