# Generated by Django 5.2.15 on 2026-07-22 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0005_remove_income_custom_denomination_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cashdenomination',
            name='custom_denomination',
        ),
        migrations.AlterField(
            model_name='cashdenomination',
            name='amount',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=12),
        ),
    ]
