# Generated by Django 5.2.15 on 2026-07-22 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0006_remove_cashdenomination_custom_denomination_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashdenomination',
            name='denomination',
            field=models.CharField(choices=[('500', '₹500'), ('200', '₹200'), ('100', '₹100'), ('50', '₹50'), ('20', '₹20'), ('10', '₹10'), ('Other', 'Other')], max_length=20),
        ),
    ]
