# Generated by Django 5.2.15 on 2026-07-07 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='balance_amount',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='training.course'),
        ),
        migrations.AlterField(
            model_name='student',
            name='course_fee',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10),
        ),
    ]
