# Generated by Django 5.2.15 on 2026-07-11 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0003_studentpayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
