# Generated by Django 5.2.15 on 2026-07-12 04:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0004_alter_student_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='trainer_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='balance_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.course'),
        ),
        migrations.AlterField(
            model_name='student',
            name='course_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
