# Generated by Django 5.2.15 on 2026-07-12 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0005_student_trainer_name_alter_student_balance_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='balance_amount',
        ),
        migrations.RemoveField(
            model_name='student',
            name='paid_amount',
        ),
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('Pending Payment', 'Pending Payment'), ('Partial Payment', 'Partial Payment'), ('Paid', 'Paid')], default='Pending Payment', max_length=30),
        ),
    ]
