# Generated by Django 5.2.15 on 2026-07-22 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0007_studentpayment_bank_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentpayment',
            name='custom_denomination',
        ),
        migrations.RemoveField(
            model_name='studentpayment',
            name='denomination',
        ),
        migrations.RemoveField(
            model_name='studentpayment',
            name='notes_count',
        ),
        migrations.CreateModel(
            name='StudentPaymentCashDenomination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denomination', models.CharField(choices=[('500', '₹500'), ('200', '₹200'), ('100', '₹100'), ('50', '₹50'), ('20', '₹20'), ('10', '₹10'), ('Coins', 'Coins'), ('Others', 'Others')], max_length=20)),
                ('custom_denomination', models.PositiveIntegerField(blank=True, null=True)),
                ('notes_count', models.PositiveIntegerField()),
                ('amount', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_denominations', to='training.studentpayment')),
            ],
        ),
    ]
