# Generated by Django 5.2.15 on 2026-07-23 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0008_remove_studentpayment_custom_denomination_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentpaymentcashdenomination',
            name='denomination',
            field=models.CharField(choices=[('500', '₹500'), ('200', '₹200'), ('100', '₹100'), ('50', '₹50'), ('20', '₹20'), ('10', '₹10')], max_length=20),
        ),
    ]
